/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class CustomerProjectForm extends ActionForm {
	
	private static final long serialVersionUID = 1L;
	private String projectID;
	private String materialCode;
	private String materialName;
	private String unit;
	private String amount;
	private String amountTotal;
	private String structure;
	private String amountTotalCust;
	
	private String custID;
	private String amount_old;
	private String amount_new;
	private String dateTime;
	private String qtyUse;
	
	private String add;
	private String update;
	private String delete;
	
	public CustomerProjectForm(){};
	public CustomerProjectForm (String projectID, String materialCode, String materialName, String structure, String amountTotal, String amountTotalCust){
		super();
		this.projectID 		= projectID;
		this.materialCode 	= materialCode;
		this.materialName 	= materialName;
		this.structure		= structure;
		this.amountTotal 	= amountTotal;
		this.amountTotalCust = amountTotalCust;
	}
	public CustomerProjectForm (String custID, String projectID, String materialCode, String materialName, String structure, 
			String amount_old, String amount_new, String amountTotal, String dateTime, String qtyUse){
		super();
		this.custID 		= custID;
		this.projectID 		= projectID;
		this.materialCode 	= materialCode;
		this.materialName 	= materialName;
		this.structure		= structure;
		this.amount_old 	= amount_old;
		this.amount_new 	= amount_new;
		this.amountTotal 	= amountTotal;
		this.dateTime		= dateTime;
		this.qtyUse			= qtyUse;
	}
	public void reset() {
		this.custID = "";
		this.custID = "";
		this.materialCode = "";
		this.materialName = "";
		this.structure = "";
		this.amount_old = "";
		this.amount_new = "";
		this.amountTotal = "";
		this.dateTime = "";
		this.qtyUse = "";
		this.update = null;
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getMaterialCode() {
		return materialCode;
	}
	public void setMaterialCode(String materialCode) {
		this.materialCode = materialCode;
	}
	public String getMaterialName() {
		return materialName;
	}
	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getAmountTotal() {
		return amountTotal;
	}
	public void setAmountTotal(String amountTotal) {
		this.amountTotal = amountTotal;
	}
	public String getStructure() {
		return structure;
	}
	public void setStructure(String structure) {
		this.structure = structure;
	}
	public String getAmountTotalCust() {
		return amountTotalCust;
	}
	public void setAmountTotalCust(String amountTotalCust) {
		this.amountTotalCust = amountTotalCust;
	}
	public String getAdd() {
		return add;
	}
	public void setAdd(String add) {
		this.add = add;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getDelete() {
		return delete;
	}
	public void setDelete(String delete) {
		this.delete = delete;
	}
	public String getProjectID() {
		return projectID;
	}
	public void setProjectID(String projectID) {
		this.projectID = projectID;
	}
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getAmount_old() {
		return amount_old;
	}
	public void setAmount_old(String amountOld) {
		amount_old = amountOld;
	}
	public String getAmount_new() {
		return amount_new;
	}
	public void setAmount_new(String amountNew) {
		amount_new = amountNew;
	}
	public String getDateTime() {
		return dateTime;
	}
	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}
	public String getQtyUse() {
		return qtyUse;
	}
	public void setQtyUse(String qtyUse) {
		this.qtyUse = qtyUse;
	}
	 
}