/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class CustomerProjectForm extends ActionForm {
	
	private static final long serialVersionUID = 1L;
	private String projectID;
	private String materialCode;
	private String materialName;
	private String unit;
	private String amount;
	private String amountTotal;
	private String structure;
	private String amountTotalCust;
	
	private String add;
	private String update;
	private String delete;
	
	public CustomerProjectForm(){};
	public CustomerProjectForm (String projectID, String materialCode, String materialName, String structure, String amountTotal, String amountTotalCust){
		super();
		this.projectID 		= projectID;
		this.materialCode 	= materialCode;
		this.materialName 	= materialName;
		this.structure		= structure;
		this.amountTotal 	= amountTotal;
		this.amountTotalCust = amountTotalCust;
}
	public void reset() {
	
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getMaterialCode() {
		return materialCode;
	}
	public void setMaterialCode(String materialCode) {
		this.materialCode = materialCode;
	}
	public String getMaterialName() {
		return materialName;
	}
	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getAmountTotal() {
		return amountTotal;
	}
	public void setAmountTotal(String amountTotal) {
		this.amountTotal = amountTotal;
	}
	public String getStructure() {
		return structure;
	}
	public void setStructure(String structure) {
		this.structure = structure;
	}
	public String getAmountTotalCust() {
		return amountTotalCust;
	}
	public void setAmountTotalCust(String amountTotalCust) {
		this.amountTotalCust = amountTotalCust;
	}
	public String getAdd() {
		return add;
	}
	public void setAdd(String add) {
		this.add = add;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getDelete() {
		return delete;
	}
	public void setDelete(String delete) {
		this.delete = delete;
	}
	public String getProjectID() {
		return projectID;
	}
	public void setProjectID(String projectID) {
		this.projectID = projectID;
	}
	 
}