/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

public class GalleryForm extends ActionForm {
	
	private static final long serialVersionUID = 1L;
	private String galleryCode;
	private String galleryName;
	private String description;
	private String amount;
	private String timeUse;
	 
	private String add;
	private String update;
	private String delete;
	
	private FormFile file;
	
	public GalleryForm(){};
	public GalleryForm (String galleryCode, String galleryName){
		super();
		this.galleryCode 	= galleryCode;
		this.galleryName 	= galleryName;
}
	public GalleryForm (String galleryCode, String galleryName, String description, String amount, String timeUse){
		super();
		this.galleryCode 	= galleryCode;
		this.galleryName 	= galleryName;
		this.description 	= description;
		this.amount 		= amount;
		this.timeUse	 	= timeUse;
}
	public void reset() {
	
	}
	
/*	@Override
    public ActionErrors validate(ActionMapping mapping,
    HttpServletRequest request) {
        ActionErrors errors = new ActionErrors();
       
        if(file.getFileSize() == 0)
             errors.add("uploadedFile", new ActionMessage("errors.file.notselected"));
        if(errors.isEmpty()){
            if(!file.getContentType().equalsIgnoreCase("image/jpeg") && !file.getContentType().equalsIgnoreCase("image/jpg")
            && !file.getContentType().equalsIgnoreCase("image/pjpeg") && !file.getContentType().equalsIgnoreCase("image/png"))
                errors.add("uploadedFile", new ActionMessage("errors.file.type", file.getFileName(),file.getContentType()));
            if(file.getFileSize() > 50000)
                errors.add("uploadedFile", new ActionMessage("errors.file.size",file.getFileName(),file.getFileSize()));
        }

        return errors;
    }  */

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getGalleryName() {
		return galleryName;
	}
	public void setGalleryName(String galleryName) {
		this.galleryName = galleryName;
	}
	public String getAdd() {
		return add;
	}
	public void setAdd(String add) {
		this.add = add;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getDelete() {
		return delete;
	}
	public void setDelete(String delete) {
		this.delete = delete;
	}
	public String getGalleryCode() {
		return galleryCode;
	}
	public void setGalleryCode(String galleryCode) {
		this.galleryCode = galleryCode;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getTimeUse() {
		return timeUse;
	}
	public void setTimeUse(String timeUse) {
		this.timeUse = timeUse;
	}
	 
}