/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class GalleryForm extends ActionForm {
	
	private static final long serialVersionUID = 1L;
	private String galleryCode;
	private String galleryName;
	
	private String add;
	private String update;
	private String delete;
	
	public GalleryForm(){};
	public GalleryForm (String galleryCode, String galleryName){
		super();
		this.galleryCode 	= galleryCode;
		this.galleryName 	= galleryName;
}
	public void reset() {
	
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getGalleryName() {
		return galleryName;
	}
	public void setGalleryName(String galleryName) {
		this.galleryName = galleryName;
	}
	public String getAdd() {
		return add;
	}
	public void setAdd(String add) {
		this.add = add;
	}
	public String getUpdate() {
		return update;
	}
	public void setUpdate(String update) {
		this.update = update;
	}
	public String getDelete() {
		return delete;
	}
	public void setDelete(String delete) {
		this.delete = delete;
	}
	public String getGalleryCode() {
		return galleryCode;
	}
	public void setGalleryCode(String galleryCode) {
		this.galleryCode = galleryCode;
	}
	 
}