/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cus.vsa.data.CusLoginDB;
import com.cus.vsa.form.CusLoginForm;
import com.vsa.util.DateUtil;
 
public class CusLoginAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CusLoginForm cusLoginForm = (CusLoginForm) form; 
		CusLoginDB cusLoginDB = new CusLoginDB();
		HttpSession session = request.getSession();
		String forwardText = null;
		String chkLogout = "";
		if(session.getAttribute("userName") != null) chkLogout = (String) session.getAttribute("userName");
		if(chkLogout.equals("logout")){
			session.removeAttribute("userName");
			session.invalidate();
			forwardText = "error";
		}else{
			
		String userName = cusLoginForm.getUserName().toLowerCase();
		String passWord = cusLoginForm.getPassWord();
		 
		if(userName != "" || passWord != "") {
			cusLoginForm = cusLoginDB.checkLogin(userName, passWord);
			if(cusLoginForm.isTrue()) {
					
					session.setAttribute("userName", cusLoginForm.getUserName());
					session.setAttribute("passWord", passWord);
					session.setAttribute("name", cusLoginForm.getName());
					session.setAttribute("type", cusLoginForm.getType());
					session.setAttribute("custID", cusLoginForm.getCustID());
					session.setAttribute("statusProj", cusLoginForm.getStatusProj());
					
					String login = "1";
					session.setAttribute("login", login); 
					String type = cusLoginForm.getType();
					
					if(type.equals("cus")){
						forwardText = "success";
					}else{
						forwardText = "error";
					}
					
					DateUtil dateUtil = new DateUtil();
					String date 	= dateUtil.curDate();
					date = dateUtil.CnvToYYYYMMDD(date, '-');
					
			} else {
				request.setAttribute("error", "Username หรือ Password ไม่ถู�?ต้อง ");
				String login = "0";
				session.setAttribute("login", login);
				forwardText = "error";
			}
		} else {
			request.setAttribute("error", "โปรดระบุ Username �?ละ Password");
			String login = "0";
			session.setAttribute("login", login);
			forwardText = "error";
		}
	}

		return mapping.findForward(forwardText);
	}
}