/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cus.vsa.data.CusLoginDB;
import com.cus.vsa.form.CusLoginForm;
import com.vsa.util.DateUtil;
 
public class EditProfileAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		CusLoginDB cusLoginDB = new CusLoginDB(); 
		CusLoginForm cusLoginForm = (CusLoginForm) form; 
		
		String hdUserName		= cusLoginForm.getHdUserName().toLowerCase();
		String userName 		= cusLoginForm.getUserName().toLowerCase();
		String oldPassWord 		= cusLoginForm.getOldPassWord();
		String passWord 		= cusLoginForm.getPassWord();
		String conFirmPassword 	= cusLoginForm.getConFirmPassword();
		String name  			= new String(cusLoginForm.getName().getBytes("ISO8859_1"), "utf-8");
		String surName  		= new String(cusLoginForm.getSurName().getBytes("ISO8859_1"), "utf-8");
		String tel				= cusLoginForm.getTel();
		
		String forwardText = "error";
		String alertMassage = "กรุณากรอกข้อมูลให้ครบ";
		
		if(oldPassWord != "" && passWord != "" && conFirmPassword != ""){
			String chkPass = "";
			chkPass = cusLoginDB.SelectPassword(userName);
			oldPassWord = cusLoginDB.encrypt(oldPassWord);
				if(oldPassWord.equals(chkPass)){
					
					if(passWord.equals(conFirmPassword)){
						cusLoginDB.ChangePassword(userName, conFirmPassword);
						alertMassage = "เปลี่ยน Password เรียบร้อยแล้ว";
						forwardText = "login";
					}else{
						alertMassage = "Password ไม่เหมือนกัน"; 
						forwardText = "error";
					}
					
				}else{
					alertMassage = "Password เก่า ไม่ถูกต้อง"; 
					forwardText = "error";
				}
			}
		
		if(userName != "" && name != "" && surName != "" && tel != "" && oldPassWord == "" && passWord == "" && conFirmPassword == ""){
			cusLoginDB.updateCustomer(name, surName, userName, tel, hdUserName);
			HttpSession session = request.getSession();
			session.setAttribute("userName", userName);
			forwardText = "success";
		}
		
		request.setAttribute("alertMassage", alertMassage);
		
		return mapping.findForward(forwardText);
	}
}