/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
 
import com.cus.vsa.data.CusLoginDB;
import com.cus.vsa.data.RequestPlanDB; 
import com.cus.vsa.form.CusLoginForm;
import com.cus.vsa.form.RequestPlanForm;
import com.vsa.util.DateUtil;
 
public class RequestPlanAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		HttpSession sessionCus = request.getSession();
		RequestPlanDB requestPlanDB = new RequestPlanDB(); 
		RequestPlanForm requestPlanForm = (RequestPlanForm) form; 
		String forwardText = "";
		String alertMassage = "กรุณากรอกข้อมูลให้ครบ";
		
		if(sessionCus.getAttribute("custID").toString() != null){
		
		String custID		= sessionCus.getAttribute("custIDCus").toString();
		String passWord		= sessionCus.getAttribute("passWordCus").toString();
		String name			= sessionCus.getAttribute("nameCus").toString().toLowerCase();
		String email 		= sessionCus.getAttribute("userNameCus").toString().toLowerCase();
		String galleryID	= requestPlanForm.getGalleryID(); // project type
		String statusProj	= "02"; // non activate
		String address		= new String(requestPlanForm.getAddress().getBytes("ISO8859_1"), "utf-8");
		
		String messageHD 	= "ขอแบบบ้าน";
		String messageDT 	= "ขอนะครับ";
		
		DateUtil dateUtil = new DateUtil();
		String dateTime 	= dateUtil.curDateTime();
		
		boolean chkProject = false;
		chkProject = requestPlanDB.CheckProject(custID);
		if(chkProject!=true){
			requestPlanDB.insertNotification(name, email, messageHD, messageDT, dateTime, "ur", "b");
			requestPlanDB.AddProjectHD("", "", custID, dateTime, galleryID, statusProj, address);
		}
		sessionCus.setAttribute("statusProjCus", statusProj);
		
		  forwardText = "success";
		}else{
		  forwardText = "nologin";
		}
		
		request.setAttribute("alertMassage", alertMassage);
		
		return mapping.findForward(forwardText);
	}
}