/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 18-06-2015
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class CusLoginForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String userName;
	private String passWord;
	private String conFirmPassword;
	private String oldPassWord;
	private String name;
	private String surName;
	private String tel;
	private String sex;
	private String type;
	private String lockScreen;
	private boolean isTrue;
	private String hdUserName;
	
	private String custID;
	private String email;
	
	public CusLoginForm(){};
	public CusLoginForm (String userName, String passWord, String name, String type){
		super();
		this.userName 	= userName;
		this.passWord	= passWord;
		this.name 		= name;
		this.type		= type;
	}
	public CusLoginForm (String userName, String passWord, String name, String surName, String tel, String type){
		super();
		this.userName 	= userName;
		this.passWord	= passWord;
		this.name 		= name;
		this.surName	= surName;
		this.tel 		= tel;
		this.type		= type;
	}
	public void reset() {
		this.passWord = "";
		this.userName = "";
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
	
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassWord() {
		return passWord;
	}
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public boolean isTrue() {
		return isTrue;
	}
	public void setTrue(boolean isTrue) {
		this.isTrue = isTrue;
	}
	public String getSurName() {
		return surName;
	}
	public void setSurName(String surName) {
		this.surName = surName;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getConFirmPassword() {
		return conFirmPassword;
	}
	public void setConFirmPassword(String conFirmPassword) {
		this.conFirmPassword = conFirmPassword;
	}
	public String getLockScreen() {
		return lockScreen;
	}
	public void setLockScreen(String lockScreen) {
		this.lockScreen = lockScreen;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getOldPassWord() {
		return oldPassWord;
	}
	public void setOldPassWord(String oldPassWord) {
		this.oldPassWord = oldPassWord;
	}
	public String getHdUserName() {
		return hdUserName;
	}
	public void setHdUserName(String hdUserName) {
		this.hdUserName = hdUserName;
	}
	public String getCustID() {
		return custID;
	}
	public void setCustID(String custID) {
		this.custID = custID;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

}