/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 18-06-2015
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class NotificationForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String no; 
	private String name; 
	private String email;
	private String dateTime;
	private String massageHD;
	private String massageDT;
	 
	public NotificationForm(){};
	public NotificationForm(String no, String name, String email, String massageHD, String massageDT, String dateTime){
		super();
		this.no 			= no;
		this.name 			= name;
		this.email			= email;
		this.massageHD 		= massageHD;
		this.massageDT 		= massageDT;
		this.dateTime		= dateTime;
	}
	 
	public void reset() {
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	public String getMassageHD() {
		return massageHD;
	}

	public void setMassageHD(String massageHD) {
		this.massageHD = massageHD;
	}

	public String getMassageDT() {
		return massageDT;
	}

	public void setMassageDT(String massageDT) {
		this.massageDT = massageDT;
	}
	public String getNo() {
		return no;
	}
	public void setNo(String no) {
		this.no = no;
	}
	
 
}