/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cus.vsa.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 18-06-2015
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class NotificationForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String no; 
	private String name; 
	private String email;
	private String dateTime;
	private String messageHD;
	private String messageDT;
	private String statusRead;
	private String statusType;
	 
	public NotificationForm(){};
	public NotificationForm(String no, String name, String email, String messageHD, String messageDT, String dateTime
			, String statusRead, String statusType){
		super();
		this.no 			= no;
		this.name 			= name;
		this.email			= email;
		this.messageHD 		= messageHD;
		this.messageDT 		= messageDT;
		this.dateTime		= dateTime;
		this.statusRead 	= statusRead;
		this.statusType		= statusType;
	}
	 
	public void reset() {
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	public String getNo() {
		return no;
	}
	public void setNo(String no) {
		this.no = no;
	}
	public String getMessageHD() {
		return messageHD;
	}
	public void setMessageHD(String messageHD) {
		this.messageHD = messageHD;
	}
	public String getMessageDT() {
		return messageDT;
	}
	public void setMessageDT(String messageDT) {
		this.messageDT = messageDT;
	}
	public String getStatusRead() {
		return statusRead;
	}
	public void setStatusRead(String statusRead) {
		this.statusRead = statusRead;
	}
	public String getStatusType() {
		return statusType;
	}
	public void setStatusType(String statusType) {
		this.statusType = statusType;
	}
	
 
}