/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.action;

import java.io.File;
import java.io.FileOutputStream;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.vsa.data.GalleryDB;
import com.vsa.form.GalleryForm;
import com.vsa.util.DateUtil;
/** 
 * MyEclipse Struts
 * Creation date: 09-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class GalleryAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		GalleryForm galleryForm = (GalleryForm) form;// TODO Auto-generated method stub
		GalleryDB galleryDB = new GalleryDB();
		String galleryCode 	= galleryForm.getGalleryCode();
		String galleryName 	= new String(galleryForm.getGalleryName().getBytes("ISO8859_1"), "utf-8");
		String description 	= new String(galleryForm.getDescription().getBytes("ISO8859_1"), "utf-8");
		String amount	 	= galleryForm.getAmount();
		String timeUse	 	= galleryForm.getTimeUse();
		
		String fileName = "", filePath = "", usePath = ""; FormFile file = null;
		
		String add 					= galleryForm.getAdd();
		String update 				= galleryForm.getUpdate();
		String delete 				= galleryForm.getDelete();
		String alertMassage			= "";
		 
		DateUtil dateUtil = new DateUtil();
		
		if(galleryForm.getFile() != null){
		file = galleryForm.getFile();
		filePath =  getServlet().getServletContext().getRealPath("//") +"\\upload";
		usePath = "upload/";
		 fileName = file.getFileName();
		}
		String date = dateUtil.CnvToYYYYMMDD(dateUtil.curDate(), '-');
		String time = dateUtil.curTime();
		String dateTime = date+" "+time;
		String forwardText = null;
	  
		if(add!=null){
			
		if(!galleryName.equals("")&&!("").equals(fileName)){
			
				String[] fname = fileName.split("\\.");
			    	fileName = fname[0];
			    //	dateTime = fname[1];
			    	dateTime = dateTime.replace(":", "-");
			    	String imageName = dateTime+"."+fname[1];
			    	
			        System.out.println("Server path:" +filePath);
			        File newFile = new File(filePath, imageName);
		              
			        if(!newFile.exists()){
			        	galleryDB.AddGallery(galleryName, description, amount, timeUse);
			        	galleryDB.AddImage(imageName, usePath+fileName, "hd");
			        	
			          FileOutputStream fos = new FileOutputStream(newFile);
			          fos.write(file.getFileData());
			          fos.flush();
			          fos.close();
			        }  
		
		List galleryList = galleryDB.GetGallery();
		request.setAttribute("galleryList", galleryList);
		
		forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}
		}
		if(update!=null){
			if(!galleryCode.equals("")&&!galleryName.equals("")){
		 
				galleryDB.UpdateGallery(galleryCode, galleryName, description, amount, timeUse);
			
				List galleryList = galleryDB.GetGallery();
				request.setAttribute("galleryList", galleryList);
			
			forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}	
		}
		if(delete!=null){
			galleryDB.DeleteGallery(galleryCode);
			
			List galleryList = galleryDB.GetGallery();
			request.setAttribute("galleryList", galleryList);
			
			forwardText = "success";
		}
 
		return mapping.findForward(forwardText);
	}
}