/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vsa.data.MaterialDB;
import com.vsa.form.MaterialForm;
import com.vsa.util.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class MaterialAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		MaterialForm materialForm = (MaterialForm) form;// TODO Auto-generated method stub
		MaterialDB materialDB = new MaterialDB();
		String materialCode 	= materialForm.getMaterialCode();
		String materialName 	= new String(materialForm.getMaterialName().getBytes("ISO8859_1"), "utf-8");
		String amount 			= materialForm.getAmount();
		String unit 			= new String(materialForm.getUnit().toUpperCase().getBytes("ISO8859_1"), "utf-8");
	 
		String add 					= materialForm.getAdd();
		String update 				= materialForm.getUpdate();
		String delete 				= materialForm.getDelete();
		String alertMassage			= "";
		 
		String forwardText = null;
	  
		if(add!=null){
			
		if(!materialName.equals("")&&!amount.equals("")&&!unit.equals("")){
		
			materialDB.AddMaterial(materialName, amount, unit);
		
		List materialList = materialDB.GetMaterialList("", "");
		request.setAttribute("materialList", materialList);
		
		forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}
		}
		if(update!=null){
			if(!materialCode.equals("")&&!materialName.equals("")&&!amount.equals("")&&!unit.equals("")){
		 
				materialDB.UpdateMaterial(materialCode, materialName, amount, unit);
			
				List materialList = materialDB.GetMaterialList("", "");
				request.setAttribute("materialList", materialList);
			
			forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}	
		}
		if(delete!=null){
			materialDB.DeleteMaterial(materialCode);
			
			List materialList = materialDB.GetMaterialList("", "");
			request.setAttribute("materialList", materialList);
			
			forwardText = "success";
		}
		
		return mapping.findForward(forwardText);
	}
}