/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.cus.vsa.data.NotificationDB;
import com.cus.vsa.form.NotificationForm;
import com.vsa.util.DateUtil;
 
public class NotificationAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		 
		NotificationDB notificationDB = new NotificationDB(); 
		NotificationForm notificationForm = (NotificationForm) form; 
		
		String no = notificationForm.getNo(); 
		 
		String forwardText = "";
		String alertMassage = "กรุณากรอกข้อมูลให้ครบ";
		
		if(no != ""){
			notificationDB.UpdateNotification(no);
			forwardText = "success";
		}else{
			forwardText = "error";
		}
		
		request.setAttribute("alertMassage", alertMassage);
		
		return mapping.findForward(forwardText);
	}
}