/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vsa.data.ProjectDB;
import com.vsa.form.ProjectForm;
import com.vsa.util.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class ProjectDTAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		ProjectForm projectForm = (ProjectForm) form;// TODO Auto-generated method stub
		ProjectDB projectDB = new ProjectDB();
		String projectID		= projectForm.getProjectID();
		String structure		= projectForm.getStructure();
		String materialCode 	= projectForm.getMaterialCode(); 
		String weight			= projectForm.getWeight();
		String amount 			= projectForm.getAmount();
		String amountTotal		= projectForm.getAmountTotal();
	 
		String add 				= projectForm.getAdd();
		String update 			= projectForm.getUpdate();
		String delete 			= projectForm.getDelete();
		String view				= projectForm.getView();
		String alertMassage			= "";
		 
		DateUtil dateUtil = new DateUtil();
		String forwardText = null;
	  
		if(add!=null){
			
		if(!projectID.equals("")&&!materialCode.equals("")&&!weight.equals("")&&!amount.equals("")&&!amountTotal.equals("")){
		
	//		projectID 	= String.valueOf(Integer.parseInt(projectID) + 1);
			 
			if (projectID.length() == 1) {
				projectID = "00000" + projectID; 
			} else if (projectID.length() == 2) {
				projectID = "0000" + projectID; 
			} else if (projectID.length() == 3) {
				projectID = "000" + projectID; 
			} else if (projectID.length() == 4) {
				projectID = "00" + projectID; 
			} else if (projectID.length() == 5) {
				projectID = "0" + projectID; 
			}
			
			projectDB.AddProjectDT(projectID, structure, materialCode, weight, amount, amountTotal);
		
		List projectDTList = projectDB.GetProjectDTList(projectID, "");
		request.setAttribute("projectDTList", projectDTList);
		
		forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}
		}
		if(update!=null){
			if(!projectID.equals("")&&!materialCode.equals("")&&!weight.equals("")&&!amount.equals("")&&!amountTotal.equals("")){
		 
				if (projectID.length() == 1) {
					projectID = "00000" + projectID; 
				} else if (projectID.length() == 2) {
					projectID = "0000" + projectID; 
				} else if (projectID.length() == 3) {
					projectID = "000" + projectID; 
				} else if (projectID.length() == 4) {
					projectID = "00" + projectID; 
				} else if (projectID.length() == 5) {
					projectID = "0" + projectID; 
				}
				
				projectDB.UpdateProjectDT(projectID, structure, materialCode, weight, amount, amountTotal);
			
				List projectDTList = projectDB.GetProjectDTList(projectID, "");
				request.setAttribute("projectDTList", projectDTList);
			
			forwardText = "success";
		}else{
			alertMassage = "กรุณา กรอก ข้อมูลให้ครบถ้วน";
			forwardText = "success";
		}	
		}
		if(delete!=null){
			
			if (projectID.length() == 1) {
				projectID = "00000" + projectID; 
			} else if (projectID.length() == 2) {
				projectID = "0000" + projectID; 
			} else if (projectID.length() == 3) {
				projectID = "000" + projectID; 
			} else if (projectID.length() == 4) {
				projectID = "00" + projectID; 
			} else if (projectID.length() == 5) {
				projectID = "0" + projectID; 
			}
			
			projectDB.DeleteProjectDT(projectID, structure, materialCode);
			
			List projectDTList = projectDB.GetProjectDTList(projectID, "");
			request.setAttribute("projectDTList", projectDTList);
			
			forwardText = "success";
		}
		
		return mapping.findForward(forwardText);
	}
}