/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vsa.data.LoginDB;
import com.vsa.form.LoginForm;
import com.vsa.util.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class RegisterAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		LoginDB loginDB = new LoginDB();
	
		String userName = loginForm.getUserName().toLowerCase();
		String passWord = loginForm.getPassWord();
		String conFirmPassword = loginForm.getConFirmPassword();
		String name = new String(loginForm.getName().getBytes("ISO8859_1"), "utf-8");
		String surName = new String(loginForm.getSurName().getBytes("ISO8859_1"), "utf-8");
		String tel = loginForm.getTel();
		 
		boolean chkRegister = false;
		
		DateUtil dateUtil = new DateUtil();
		String date = dateUtil.CnvToYYYYMMDD(dateUtil.curDate(), '-');
		
		String forwardText = "success";
		
		if(userName != "" && passWord != "" && conFirmPassword != "" && name != "" && surName != "" && tel != "" && userName != null 
				&& passWord != null && conFirmPassword != null && name != null && surName != null && tel != null) {
			
			if(passWord.equals(conFirmPassword)){
				name = name+" "+surName;
				chkRegister = loginDB.ChkRegister(userName, name);
				if(chkRegister==true){
					request.setAttribute("alertMessage", "Password ซ้ำ");
					request.setAttribute("lockScreen", "register");
				}else{
					loginDB.registerNew(userName, passWord, name, "amd", date, tel);
					request.setAttribute("lockScreen", "login");
				}
			}else{
				request.setAttribute("alertMessage", "Password ไม่ตรงกัน ");
				request.setAttribute("lockScreen", "register");
			}
		
		} else {
				request.setAttribute("alertMessage", "กรุณากรอกข้อมูลให้ครบถ้วน ");
				request.setAttribute("lockScreen", "register");
		}
		
		return mapping.findForward(forwardText);
	}
}